# frozen_string_literal: true

source("https://rubygems.org")

gem("foo", path: "../gems/foo")
gem("bar", path: "../gems/bar")
gem("baz", path: "../gems/baz")
gem("qux", path: "../gems/qux", require: false)
gem("tapioca", path: "../../../")

gem("psych")
# `extras` gem is causing problems by modifying
# `Shellwords` functionaly. Depending on it to
# ensure that we don't fail.
gem("extras")
# Needed for DSL generation tests. The simplest
# gem that we have a DSL generator for.
gem("smart_properties")
gem("activesupport")
# Needed to test Git gems
gem("ast", git: "https://github.com/whitequark/ast", ref: "e07a4f66e05ac7972643a8841e336d327ea78ae1")
# Needed to test missing gems
gem("nokogiri")
