# frozen_string_literal: true

source("https://rubygems.org")

gem("foo", path: "../gems/foo")
gem("bar", path: "../gems/bar")
gem("baz", path: "../gems/baz")
gem("qux", path: "../gems/qux", require: false)
gem("tapioca", path: "../../../")

gem("psych")
# `extras` gem is causing problems by modifying
# `Shellwords` functionaly. Depending on it to
# ensure that we don't fail.
gem("extras")
# Needed for DSL generation tests. The simplest
# gems that we have a DSL generator for.
gem("rake", "13.0.6")
gem("smart_properties", "1.15.0")
gem("sidekiq", "6.2.1")
gem("activesupport", "6.1.3.2")
# Needed to test Git gems
gem("ast", git: "https://github.com/whitequark/ast", ref: "e07a4f66e05ac7972643a8841e336d327ea78ae1")

# Needed to test missing gems
platform :truffleruby do
  gem "minitest-excludes"
end
