# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `erb` gem.
# Please instead update this file by running `bin/tapioca gem erb`.

# source://erb//erb/compiler.rb#100
ERB::Compiler::Scanner::DEFAULT_ETAGS = T.let(T.unsafe(nil), Array)

# source://erb//erb/compiler.rb#99
ERB::Compiler::Scanner::DEFAULT_STAGS = T.let(T.unsafe(nil), Array)

module ERB::Escape
  private

  def html_escape(_arg0); end

  class << self
    def html_escape(_arg0); end
  end
end

# source://erb//erb.rb#356
ERB::NOT_GIVEN = T.let(T.unsafe(nil), Object)

module ERB::Util
  include ::ERB::Escape
end

# source://erb//erb/version.rb#3
ERB::VERSION = T.let(T.unsafe(nil), String)
