# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `faraday-gzip` gem.
# Please instead update this file by running `bin/tapioca gem faraday-gzip`.


# source://faraday-gzip//lib/faraday/gzip/middleware.rb#5
module Faraday; end

# Middleware main module.
#
# source://faraday-gzip//lib/faraday/gzip/middleware.rb#6
module Faraday::Gzip; end

# Middleware to automatically decompress response bodies. If the
# "Accept-Encoding" header wasn't set in the request, this sets it to
# "gzip,deflate" and appropriately handles the compressed response from the
# server. This resembles what Ruby 1.9+ does internally in Net::HTTP#get.
# Based on https://github.com/lostisland/faraday_middleware/blob/main/lib/faraday_middleware/gzip.rb
#
# source://faraday-gzip//lib/faraday/gzip/middleware.rb#13
class Faraday::Gzip::Middleware < ::Faraday::Middleware
  # source://faraday-gzip//lib/faraday/gzip/middleware.rb#79
  def brotli_inflate(body); end

  # source://faraday-gzip//lib/faraday/gzip/middleware.rb#34
  def call(env); end

  # source://faraday-gzip//lib/faraday/gzip/middleware.rb#65
  def inflate(body); end

  # source://faraday-gzip//lib/faraday/gzip/middleware.rb#83
  def raw_body(body); end

  # source://faraday-gzip//lib/faraday/gzip/middleware.rb#52
  def reset_body(env); end

  # source://faraday-gzip//lib/faraday/gzip/middleware.rb#59
  def uncompress_gzip(body); end

  private

  # @return [Boolean]
  #
  # source://faraday-gzip//lib/faraday/gzip/middleware.rb#89
  def empty_body?(response_env); end

  class << self
    # source://faraday-gzip//lib/faraday/gzip/middleware.rb#14
    def optional_dependency(lib = T.unsafe(nil)); end

    # source://faraday-gzip//lib/faraday/gzip/middleware.rb#23
    def supported_encodings; end
  end
end

# source://faraday-gzip//lib/faraday/gzip/middleware.rb#29
Faraday::Gzip::Middleware::ACCEPT_ENCODING = T.let(T.unsafe(nil), String)

# source://faraday-gzip//lib/faraday/gzip/middleware.rb#21
Faraday::Gzip::Middleware::BROTLI_SUPPORTED = T.let(T.unsafe(nil), FalseClass)

# source://faraday-gzip//lib/faraday/gzip/middleware.rb#30
Faraday::Gzip::Middleware::CONTENT_ENCODING = T.let(T.unsafe(nil), String)

# source://faraday-gzip//lib/faraday/gzip/middleware.rb#31
Faraday::Gzip::Middleware::CONTENT_LENGTH = T.let(T.unsafe(nil), String)

# source://faraday-gzip//lib/faraday/gzip/middleware.rb#32
Faraday::Gzip::Middleware::SUPPORTED_ENCODINGS = T.let(T.unsafe(nil), String)

# source://faraday-gzip//lib/faraday/gzip/version.rb#5
Faraday::Gzip::VERSION = T.let(T.unsafe(nil), String)
