# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `json` gem.
# Please instead update this file by running `bin/tapioca gem json`.

# source://json//json/common.rb#114
JSON::CREATE_ID_TLS_KEY = T.let(T.unsafe(nil), String)

# source://json//json/common.rb#111
JSON::DEFAULT_CREATE_ID = T.let(T.unsafe(nil), String)

# For backwards compatibility
#
# source://json//json/common.rb#159
JSON::UnparserError = JSON::GeneratorError
