# typed: false

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `net-protocol` gem.
# Please instead update this file by running `bin/tapioca gem net-protocol`.


# pkg:gem/net-protocol#lib/net/protocol.rb:151
class Net::BufferedIO
  # pkg:gem/net-protocol#lib/net/protocol.rb:152
  def initialize(io, read_timeout: T.unsafe(nil), write_timeout: T.unsafe(nil), continue_timeout: T.unsafe(nil), debug_output: T.unsafe(nil)); end

  # pkg:gem/net-protocol#lib/net/protocol.rb:344
  def <<(*strs); end

  # pkg:gem/net-protocol#lib/net/protocol.rb:181
  def close; end

  # pkg:gem/net-protocol#lib/net/protocol.rb:177
  def closed?; end

  # pkg:gem/net-protocol#lib/net/protocol.rb:166
  def continue_timeout; end

  # pkg:gem/net-protocol#lib/net/protocol.rb:166
  def continue_timeout=(_arg0); end

  # pkg:gem/net-protocol#lib/net/protocol.rb:167
  def debug_output; end

  # pkg:gem/net-protocol#lib/net/protocol.rb:167
  def debug_output=(_arg0); end

  # pkg:gem/net-protocol#lib/net/protocol.rb:173
  def eof?; end

  # pkg:gem/net-protocol#lib/net/protocol.rb:169
  def inspect; end

  # pkg:gem/net-protocol#lib/net/protocol.rb:163
  def io; end

  # pkg:gem/net-protocol#lib/net/protocol.rb:191
  def read(len, dest = T.unsafe(nil), ignore_eof = T.unsafe(nil)); end

  # pkg:gem/net-protocol#lib/net/protocol.rb:212
  def read_all(dest = T.unsafe(nil)); end

  # pkg:gem/net-protocol#lib/net/protocol.rb:164
  def read_timeout; end

  # pkg:gem/net-protocol#lib/net/protocol.rb:164
  def read_timeout=(_arg0); end

  # pkg:gem/net-protocol#lib/net/protocol.rb:261
  def readline; end

  # pkg:gem/net-protocol#lib/net/protocol.rb:230
  def readuntil(terminator, ignore_eof = T.unsafe(nil), limit: T.unsafe(nil)); end

  # pkg:gem/net-protocol#lib/net/protocol.rb:338
  def write(*strs); end

  # pkg:gem/net-protocol#lib/net/protocol.rb:165
  def write_timeout; end

  # pkg:gem/net-protocol#lib/net/protocol.rb:165
  def write_timeout=(_arg0); end

  # pkg:gem/net-protocol#lib/net/protocol.rb:346
  def writeline(str); end

  private

  # pkg:gem/net-protocol#lib/net/protocol.rb:409
  def LOG(msg); end

  # pkg:gem/net-protocol#lib/net/protocol.rb:400
  def LOG_off; end

  # pkg:gem/net-protocol#lib/net/protocol.rb:405
  def LOG_on; end

  # pkg:gem/net-protocol#lib/net/protocol.rb:310
  def rbuf_consume(len = T.unsafe(nil)); end

  # pkg:gem/net-protocol#lib/net/protocol.rb:306
  def rbuf_consume_all; end

  # pkg:gem/net-protocol#lib/net/protocol.rb:269
  def rbuf_fill; end

  # pkg:gem/net-protocol#lib/net/protocol.rb:294
  def rbuf_flush; end

  # pkg:gem/net-protocol#lib/net/protocol.rb:302
  def rbuf_size; end

  # pkg:gem/net-protocol#lib/net/protocol.rb:364
  def write0(*strs); end

  # pkg:gem/net-protocol#lib/net/protocol.rb:354
  def writing; end
end

# pkg:gem/net-protocol#lib/net/protocol.rb:416
class Net::InternetMessageIO < ::Net::BufferedIO
  # pkg:gem/net-protocol#lib/net/protocol.rb:417
  def initialize(*_arg0, **_arg1); end

  # *library private* (cannot handle 'break')
  #
  # pkg:gem/net-protocol#lib/net/protocol.rb:439
  def each_list_item; end

  # Read
  #
  # pkg:gem/net-protocol#lib/net/protocol.rb:426
  def each_message_chunk; end

  # Write
  #
  # pkg:gem/net-protocol#lib/net/protocol.rb:457
  def write_message(src); end

  # pkg:gem/net-protocol#lib/net/protocol.rb:445
  def write_message_0(src); end

  # pkg:gem/net-protocol#lib/net/protocol.rb:470
  def write_message_by_block(&block); end

  private

  # pkg:gem/net-protocol#lib/net/protocol.rb:513
  def buffer_filling(buf, src); end

  # pkg:gem/net-protocol#lib/net/protocol.rb:489
  def dot_stuff(s); end

  # pkg:gem/net-protocol#lib/net/protocol.rb:505
  def each_crlf_line(src); end

  # pkg:gem/net-protocol#lib/net/protocol.rb:493
  def using_each_crlf_line; end
end

# pkg:gem/net-protocol#lib/net/protocol.rb:595
Net::NetPrivate::Socket = Net::InternetMessageIO

# pkg:gem/net-protocol#lib/net/protocol.rb:79
Net::ProtocRetryError = Net::ProtoRetriableError

# pkg:gem/net-protocol#lib/net/protocol.rb:28
class Net::Protocol
  private

  # pkg:gem/net-protocol#lib/net/protocol.rb:40
  def ssl_socket_connect(s, timeout); end

  class << self
    # pkg:gem/net-protocol#lib/net/protocol.rb:32
    def protocol_param(name, val); end
  end
end

# pkg:gem/net-protocol#lib/net/protocol.rb:59
Net::Protocol::TCP_SOCKET_NEW_HAS_OPEN_TIMEOUT = T.let(T.unsafe(nil), TrueClass)

# pkg:gem/net-protocol#lib/net/protocol.rb:29
Net::Protocol::VERSION = T.let(T.unsafe(nil), String)

# pkg:gem/net-protocol#lib/net/protocol.rb:570
class Net::ReadAdapter
  # pkg:gem/net-protocol#lib/net/protocol.rb:571
  def initialize(block); end

  # pkg:gem/net-protocol#lib/net/protocol.rb:579
  def <<(str); end

  # pkg:gem/net-protocol#lib/net/protocol.rb:575
  def inspect; end

  private

  # This method is needed because @block must be called by yield,
  # not Proc#call.  You can see difference when using `break' in
  # the block.
  #
  # pkg:gem/net-protocol#lib/net/protocol.rb:588
  def call_block(str); end
end

# ReadLimitExceeded, a subclass of ProtocolError, is raised if the
# terminator is not found within the byte limit given to
# Net::BufferedIO#readuntil.
#
# The limit is the largest result readuntil may return, counting the
# terminator itself, so a limit of 4 accepts "abc\n" and rejects
# "abcd\n". Unlike the limit of IO#gets it never truncates a result to
# fit. Either the whole thing comes back or this is raised, except
# under ignore_eof, which still returns what was buffered when the
# stream ended. The count is in bytes while the IO hands back binary
# strings, which every real one does.
#
# It bounds one call, not a connection. The unconsumed buffer can
# still run one BUFSIZE past the limit, and a peer sending endless
# short lines is not bounded at all.
#
# Nothing is consumed when this is raised, so the usual response is to
# close the connection rather than read on under a wider limit.
#
# pkg:gem/net-protocol#lib/net/protocol.rb:102
class Net::ReadLimitExceeded < ::Net::ProtocolError; end

# ReadTimeout, a subclass of Timeout::Error, is raised if a chunk of the
# response cannot be read within the read_timeout.
#
# pkg:gem/net-protocol#lib/net/protocol.rb:114
class Net::ReadTimeout < ::Timeout::Error
  # :stopdoc:
  #
  # pkg:gem/net-protocol#lib/net/protocol.rb:116
  def initialize(io = T.unsafe(nil)); end

  # pkg:gem/net-protocol#lib/net/protocol.rb:119
  def io; end

  # pkg:gem/net-protocol#lib/net/protocol.rb:121
  def message; end
end

# The writer adapter class
#
# pkg:gem/net-protocol#lib/net/protocol.rb:539
class Net::WriteAdapter
  # :stopdoc:
  #
  # pkg:gem/net-protocol#lib/net/protocol.rb:541
  def initialize(writer); end

  # pkg:gem/net-protocol#lib/net/protocol.rb:555
  def <<(str); end

  # pkg:gem/net-protocol#lib/net/protocol.rb:545
  def inspect; end

  # pkg:gem/net-protocol#lib/net/protocol.rb:553
  def print(str); end

  # pkg:gem/net-protocol#lib/net/protocol.rb:564
  def printf(*args); end

  # pkg:gem/net-protocol#lib/net/protocol.rb:560
  def puts(str = T.unsafe(nil)); end

  # pkg:gem/net-protocol#lib/net/protocol.rb:549
  def write(str); end
end

# WriteTimeout, a subclass of Timeout::Error, is raised if a chunk of the
# response cannot be written within the write_timeout.  Not raised on Windows.
#
# pkg:gem/net-protocol#lib/net/protocol.rb:134
class Net::WriteTimeout < ::Timeout::Error
  # :stopdoc:
  #
  # pkg:gem/net-protocol#lib/net/protocol.rb:136
  def initialize(io = T.unsafe(nil)); end

  # pkg:gem/net-protocol#lib/net/protocol.rb:139
  def io; end

  # pkg:gem/net-protocol#lib/net/protocol.rb:141
  def message; end
end
