# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `resolv` gem.
# Please instead update this file by running `bin/tapioca gem resolv`.

# source://resolv//resolv.rb#617
Resolv::DNS::RequestID = T.let(T.unsafe(nil), Hash)

# source://resolv//resolv.rb#618
Resolv::DNS::RequestIDMutex = T.let(T.unsafe(nil), Thread::Mutex)

# Standard (class generic) RRs
#
# source://resolv//resolv.rb#1807
Resolv::DNS::Resource::ClassValue = T.let(T.unsafe(nil), T.untyped)

# IPv6 link local address format fe80:b:c:d:e:f:g:h%em1
#
# source://resolv//resolv.rb#2464
Resolv::IPv6::Regex_8HexLinkLocal = T.let(T.unsafe(nil), Regexp)

# Compressed IPv6 link local address format fe80::b%em1
#
# source://resolv//resolv.rb#2473
Resolv::IPv6::Regex_CompressedHexLinkLocal = T.let(T.unsafe(nil), Regexp)
