# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rubydex` gem.
# Please instead update this file by running `bin/tapioca gem rubydex`.


# frozen_string_literal: true
# typed: strict

# pkg:gem/rubydex#lib/rubydex/version.rb:3
module Rubydex; end

class Rubydex::AttrAccessorDefinition < ::Rubydex::Definition; end
class Rubydex::AttrReaderDefinition < ::Rubydex::Definition; end
class Rubydex::AttrWriterDefinition < ::Rubydex::Definition; end
class Rubydex::Class < ::Rubydex::Namespace; end
class Rubydex::ClassDefinition < ::Rubydex::Definition; end
class Rubydex::ClassVariable < ::Rubydex::Declaration; end
class Rubydex::ClassVariableDefinition < ::Rubydex::Definition; end

# pkg:gem/rubydex#lib/rubydex/comment.rb:4
class Rubydex::Comment
  # pkg:gem/rubydex#lib/rubydex/comment.rb:12
  sig { params(string: String, location: Rubydex::Location).void }
  def initialize(string:, location:); end

  # pkg:gem/rubydex#lib/rubydex/comment.rb:9
  sig { returns(Rubydex::Location) }
  def location; end

  # pkg:gem/rubydex#lib/rubydex/comment.rb:6
  sig { returns(String) }
  def string; end
end

class Rubydex::Constant < ::Rubydex::Declaration; end
class Rubydex::ConstantAlias < ::Rubydex::Declaration; end
class Rubydex::ConstantAliasDefinition < ::Rubydex::Definition; end
class Rubydex::ConstantDefinition < ::Rubydex::Definition; end

class Rubydex::ConstantReference < ::Rubydex::Reference
  def initialize(_arg0, _arg1); end

  sig { returns(Rubydex::Location) }
  def location; end

  sig { returns(String) }
  def name; end
end

class Rubydex::Declaration
  def initialize(_arg0, _arg1); end

  sig { returns(T::Enumerable[Rubydex::Definition]) }
  def definitions; end

  sig { returns(String) }
  def name; end

  sig { returns(Rubydex::Declaration) }
  def owner; end

  sig { returns(T::Enumerable[Rubydex::Reference]) }
  def references; end

  sig { returns(String) }
  def unqualified_name; end

  class << self
    private

    # pkg:gem/rubydex#lib/rubydex.rb:10
    def new(*_arg0); end
  end
end

class Rubydex::Definition
  def initialize(_arg0, _arg1); end

  sig { returns(T::Array[Rubydex::Comment]) }
  def comments; end

  sig { returns(T::Boolean) }
  def deprecated?; end

  sig { returns(Rubydex::Location) }
  def location; end

  sig { returns(String) }
  def name; end

  sig { returns(T.nilable(Rubydex::Location)) }
  def name_location; end

  class << self
    private

    # pkg:gem/rubydex#lib/rubydex.rb:10
    def new(*_arg0); end
  end
end

# pkg:gem/rubydex#lib/rubydex/diagnostic.rb:4
class Rubydex::Diagnostic
  # pkg:gem/rubydex#lib/rubydex/diagnostic.rb:15
  sig { params(rule: Symbol, message: String, location: Rubydex::Location).void }
  def initialize(rule:, message:, location:); end

  # pkg:gem/rubydex#lib/rubydex/diagnostic.rb:12
  sig { returns(Rubydex::Location) }
  def location; end

  # pkg:gem/rubydex#lib/rubydex/diagnostic.rb:9
  sig { returns(String) }
  def message; end

  # pkg:gem/rubydex#lib/rubydex/diagnostic.rb:6
  sig { returns(Symbol) }
  def rule; end
end

# A one based location intended for display purposes. This is what should be used when displaying a location to users,
# like in CLIs
#
# pkg:gem/rubydex#lib/rubydex/location.rb:70
class Rubydex::DisplayLocation < ::Rubydex::Location
  # Normalize to zero-based for comparison with Location
  #
  # pkg:gem/rubydex#lib/rubydex/location.rb:81
  sig { returns([String, Integer, Integer, Integer, Integer]) }
  def comparable_values; end

  # Returns itself
  #
  # pkg:gem/rubydex#lib/rubydex/location.rb:74
  sig { returns(Rubydex::DisplayLocation) }
  def to_display; end

  # pkg:gem/rubydex#lib/rubydex/location.rb:86
  sig { returns(String) }
  def to_s; end
end

class Rubydex::Document
  def initialize(_arg0, _arg1); end

  sig { returns(T::Enumerable[Rubydex::Definition]) }
  def definitions; end

  sig { returns(String) }
  def uri; end

  class << self
    private

    # pkg:gem/rubydex#lib/rubydex.rb:10
    def new(*_arg0); end
  end
end

class Rubydex::Error < StandardError; end

# pkg:gem/rubydex#lib/rubydex/failures.rb:4
class Rubydex::Failure
  # pkg:gem/rubydex#lib/rubydex/failures.rb:9
  sig { params(message: String).void }
  def initialize(message); end

  # pkg:gem/rubydex#lib/rubydex/failures.rb:6
  sig { returns(String) }
  def message; end
end

class Rubydex::GlobalVariable < ::Rubydex::Declaration; end
class Rubydex::GlobalVariableAliasDefinition < ::Rubydex::Definition; end
class Rubydex::GlobalVariableDefinition < ::Rubydex::Definition; end

# The global graph representing all declarations and their relationships for the workspace
#
# Note: this class is partially defined in C to integrate with the Rust backend
#
# pkg:gem/rubydex#lib/rubydex/graph.rb:7
class Rubydex::Graph
  # pkg:gem/rubydex#lib/rubydex/graph.rb:20
  sig { params(workspace_path: T.nilable(String)).void }
  def initialize(workspace_path: T.unsafe(nil)); end

  def [](_arg0); end

  sig { returns(T::Array[Rubydex::Failure]) }
  def check_integrity; end

  sig { returns(T::Enumerable[Rubydex::ConstantReference]) }
  def constant_references; end

  sig { returns(T::Enumerable[Rubydex::Declaration]) }
  def declarations; end

  def delete_document(_arg0); end

  sig { returns(T::Array[Rubydex::Diagnostic]) }
  def diagnostics; end

  sig { returns(T::Enumerable[Rubydex::Document]) }
  def documents; end

  def encoding=(_arg0); end
  def index_all(_arg0); end
  def index_source(_arg0, _arg1, _arg2); end

  # Index all files and dependencies of the workspace that exists in `@workspace_path`
  #
  # pkg:gem/rubydex#lib/rubydex/graph.rb:26
  sig { returns(T::Array[String]) }
  def index_workspace; end

  sig { returns(T::Enumerable[Rubydex::MethodReference]) }
  def method_references; end

  def require_paths(_arg0); end

  sig { returns(T.self_type) }
  def resolve; end

  def resolve_constant(_arg0, _arg1); end
  def resolve_require_path(_arg0, _arg1); end
  def search(_arg0); end

  # pkg:gem/rubydex#lib/rubydex/graph.rb:17
  sig { returns(String) }
  def workspace_path; end

  # pkg:gem/rubydex#lib/rubydex/graph.rb:17
  def workspace_path=(_arg0); end

  # Returns all workspace paths that should be indexed, excluding directories that we don't need to descend into such
  # as `.git`, `node_modules`. Also includes any top level Ruby files
  #
  # pkg:gem/rubydex#lib/rubydex/graph.rb:34
  sig { returns(T::Array[String]) }
  def workspace_paths; end

  private

  # Searches for the latest installation of the `rbs` gem and adds the paths for the core and stdlib RBS definitions
  # to the list of paths. This method does not require `rbs` to be a part of the bundle. It searches for whatever
  # latest installation of `rbs` exists in the system and fails silently if we can't find one
  #
  # pkg:gem/rubydex#lib/rubydex/graph.rb:81
  sig { params(paths: T::Array[String]).void }
  def add_core_rbs_definition_paths(paths); end

  # Gathers the paths we have to index for all workspace dependencies
  #
  # pkg:gem/rubydex#lib/rubydex/graph.rb:57
  sig { params(paths: T::Array[String]).void }
  def add_workspace_dependency_paths(paths); end
end

# pkg:gem/rubydex#lib/rubydex/graph.rb:8
Rubydex::Graph::IGNORED_DIRECTORIES = T.let(T.unsafe(nil), Array)

class Rubydex::InstanceVariable < ::Rubydex::Declaration; end
class Rubydex::InstanceVariableDefinition < ::Rubydex::Definition; end

# pkg:gem/rubydex#lib/rubydex/failures.rb:14
class Rubydex::IntegrityFailure < ::Rubydex::Failure; end

# A zero based internal location. Intended to be used for tool-to-tool communication, such as a language server
# communicating with an editor.
#
# pkg:gem/rubydex#lib/rubydex/location.rb:6
class Rubydex::Location
  include ::Comparable

  # pkg:gem/rubydex#lib/rubydex/location.rb:18
  sig { params(uri: String, start_line: Integer, end_line: Integer, start_column: Integer, end_column: Integer).void }
  def initialize(uri:, start_line:, end_line:, start_column:, end_column:); end

  # pkg:gem/rubydex#lib/rubydex/location.rb:38
  sig { params(other: T.untyped).returns(T.nilable(Integer)) }
  def <=>(other); end

  # pkg:gem/rubydex#lib/rubydex/location.rb:45
  sig { returns([String, Integer, Integer, Integer, Integer]) }
  def comparable_values; end

  # pkg:gem/rubydex#lib/rubydex/location.rb:15
  sig { returns(Integer) }
  def end_column; end

  # pkg:gem/rubydex#lib/rubydex/location.rb:15
  sig { returns(Integer) }
  def end_line; end

  # pkg:gem/rubydex#lib/rubydex/location.rb:15
  sig { returns(Integer) }
  def start_column; end

  # pkg:gem/rubydex#lib/rubydex/location.rb:15
  sig { returns(Integer) }
  def start_line; end

  # Turns this zero based location into a one based location for display purposes.
  #
  # pkg:gem/rubydex#lib/rubydex/location.rb:52
  sig { returns(Rubydex::DisplayLocation) }
  def to_display; end

  # pkg:gem/rubydex#lib/rubydex/location.rb:27
  sig { returns(String) }
  def to_file_path; end

  # pkg:gem/rubydex#lib/rubydex/location.rb:63
  sig { returns(String) }
  def to_s; end

  # pkg:gem/rubydex#lib/rubydex/location.rb:12
  sig { returns(String) }
  def uri; end
end

# pkg:gem/rubydex#lib/rubydex/location.rb:7
class Rubydex::Location::NotFileUriError < ::StandardError; end

class Rubydex::Method < ::Rubydex::Declaration; end
class Rubydex::MethodAliasDefinition < ::Rubydex::Definition; end
class Rubydex::MethodDefinition < ::Rubydex::Definition; end

class Rubydex::MethodReference < ::Rubydex::Reference
  def initialize(_arg0, _arg1); end

  sig { returns(Rubydex::Location) }
  def location; end

  sig { returns(String) }
  def name; end
end

class Rubydex::Module < ::Rubydex::Namespace; end
class Rubydex::ModuleDefinition < ::Rubydex::Definition; end

class Rubydex::Namespace < ::Rubydex::Declaration
  sig { returns(T::Enumerable[Rubydex::Namespace]) }
  def ancestors; end

  sig { returns(T::Enumerable[Rubydex::Namespace]) }
  def descendants; end

  def find_member(*_arg0); end
  def member(_arg0); end

  sig { returns(T.nilable(Rubydex::SingletonClass)) }
  def singleton_class; end
end

class Rubydex::Reference
  def initialize(_arg0, _arg1); end

  class << self
    private

    # pkg:gem/rubydex#lib/rubydex.rb:10
    def new(*_arg0); end
  end
end

class Rubydex::SingletonClass < ::Rubydex::Namespace; end
class Rubydex::SingletonClassDefinition < ::Rubydex::Definition; end
class Rubydex::Todo < ::Rubydex::Namespace; end

# pkg:gem/rubydex#lib/rubydex/version.rb:4
Rubydex::VERSION = T.let(T.unsafe(nil), String)
