# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `vernier` gem.
# Please instead update this file by running `bin/tapioca gem vernier`.


# pkg:gem/vernier#lib/vernier/version.rb:3
module Vernier
  class << self
    # pkg:gem/vernier#lib/vernier/marker.rb:3
    def memory_rss; end

    # pkg:gem/vernier#lib/vernier.rb:24
    def profile(mode: T.unsafe(nil), **collector_options); end

    # pkg:gem/vernier#lib/vernier.rb:40
    def run(mode: T.unsafe(nil), **collector_options); end

    # pkg:gem/vernier#lib/vernier.rb:45
    def start_profile(mode: T.unsafe(nil), **collector_options); end

    # pkg:gem/vernier#lib/vernier.rb:57
    def stop_profile; end

    # pkg:gem/vernier#lib/vernier.rb:39
    def trace(mode: T.unsafe(nil), **collector_options); end

    # pkg:gem/vernier#lib/vernier.rb:66
    def trace_retained(**profile_options, &block); end
  end
end

# pkg:gem/vernier#lib/vernier/marker.rb:3
class Vernier::Collector
  # @return [Collector] a new instance of Collector
  #
  # pkg:gem/vernier#lib/vernier/collector.rb:112
  def initialize(mode, options = T.unsafe(nil)); end

  # pkg:gem/vernier#lib/vernier/collector.rb:164
  def add_marker(name:, start:, finish:, thread: T.unsafe(nil), phase: T.unsafe(nil), data: T.unsafe(nil)); end

  # Get the current time.
  #
  # This method returns the current time from Process.clock_gettime in
  # integer nanoseconds.  It's the same time used by Vernier internals and
  # can be used to generate timestamps for custom markers.
  #
  # pkg:gem/vernier#lib/vernier/collector.rb:160
  def current_time; end

  # Record an interval with a category and name.  Yields to a block and
  # records the amount of time spent in the block as an interval marker.
  #
  # pkg:gem/vernier#lib/vernier/collector.rb:176
  def record_interval(category, name = T.unsafe(nil)); end

  # Returns the value of attribute stack_table.
  #
  # pkg:gem/vernier#lib/vernier/collector.rb:137
  def stack_table; end

  # pkg:gem/vernier#lib/vernier/collector.rb:189
  def stop; end

  private

  # pkg:gem/vernier#lib/vernier/collector.rb:139
  def add_hook(hook); end

  class << self
    # pkg:gem/vernier#lib/vernier/collector.rb:97
    def new(mode, options = T.unsafe(nil)); end
  end
end

# pkg:gem/vernier#lib/vernier/collector.rb:8
class Vernier::Collector::CustomCollector < ::Vernier::Collector
  # @return [CustomCollector] a new instance of CustomCollector
  #
  # pkg:gem/vernier#lib/vernier/collector.rb:9
  def initialize(mode, options); end

  # pkg:gem/vernier#lib/vernier/collector.rb:27
  def finish; end

  # pkg:gem/vernier#lib/vernier/collector.rb:19
  def sample; end

  # pkg:gem/vernier#lib/vernier/collector.rb:24
  def start; end
end

# pkg:gem/vernier#lib/vernier/collector.rb:47
class Vernier::Collector::RetainedCollector < ::Vernier::Collector
  # @return [RetainedCollector] a new instance of RetainedCollector
  #
  # pkg:gem/vernier#lib/vernier/collector.rb:48
  def initialize(mode, options); end

  # pkg:gem/vernier#lib/vernier/collector.rb:60
  def drain; end

  # pkg:gem/vernier#lib/vernier/collector.rb:64
  def finish; end

  # pkg:gem/vernier#lib/vernier/collector.rb:56
  def start; end
end

# pkg:gem/vernier#lib/vernier/marker.rb:3
class Vernier::Collector::TimeCollector < ::Vernier::Collector
  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def start; end

  private

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def finish; end

  class << self
    # pkg:gem/vernier#lib/vernier/marker.rb:3
    def new(_arg0, _arg1); end
  end
end

# pkg:gem/vernier#lib/vernier.rb:20
class Vernier::Error < ::StandardError; end

# Plan: The heap tracker can be in a few states:
#  * Idle
#  * Collecting
#    * Watching for new objects
#    * Watching for freed objects
#  * Draining
#    * Ignoring new objects
#    * Watching for freed objects
#  * Locked
#    * Ignoring new objects
#    * Ignoring freed objects
#    * Marking all existing objects (not yet implemented)
#    * N.B. This prevents any objects which the tracker has seen from being GC'd
#
# pkg:gem/vernier#lib/vernier/marker.rb:3
class Vernier::HeapTracker
  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def allocated_objects; end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def collect; end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def data; end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def drain; end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def freed_objects; end

  # pkg:gem/vernier#lib/vernier/heap_tracker.rb:24
  def inspect; end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def lock; end

  # pkg:gem/vernier#lib/vernier/heap_tracker.rb:41
  def stack(obj); end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def stack_idx(_arg0); end

  # Returns the value of attribute stack_table.
  #
  # pkg:gem/vernier#lib/vernier/heap_tracker.rb:18
  def stack_table; end

  # pkg:gem/vernier#lib/vernier/heap_tracker.rb:34
  def track; end

  class << self
    # pkg:gem/vernier#lib/vernier/marker.rb:3
    def _new(_arg0); end

    # pkg:gem/vernier#lib/vernier/heap_tracker.rb:20
    def new(stack_table = T.unsafe(nil)); end

    # pkg:gem/vernier#lib/vernier/heap_tracker.rb:28
    def track(&block); end
  end
end

# pkg:gem/vernier#lib/vernier/hooks.rb:4
module Vernier::Hooks; end

# pkg:gem/vernier#lib/vernier/hooks/active_support.rb:5
class Vernier::Hooks::ActiveSupport
  # @return [ActiveSupport] a new instance of ActiveSupport
  #
  # pkg:gem/vernier#lib/vernier/hooks/active_support.rb:155
  def initialize(collector); end

  # pkg:gem/vernier#lib/vernier/hooks/active_support.rb:182
  def disable; end

  # pkg:gem/vernier#lib/vernier/hooks/active_support.rb:159
  def enable; end

  # pkg:gem/vernier#lib/vernier/hooks/active_support.rb:187
  def firefox_marker_schema; end
end

# pkg:gem/vernier#lib/vernier/hooks/active_support.rb:6
Vernier::Hooks::ActiveSupport::FIREFOX_MARKER_SCHEMA = T.let(T.unsafe(nil), Array)

# pkg:gem/vernier#lib/vernier/hooks/active_support.rb:148
Vernier::Hooks::ActiveSupport::SERIALIZED_KEYS = T.let(T.unsafe(nil), Hash)

# pkg:gem/vernier#lib/vernier/hooks/memory_usage.rb:5
class Vernier::Hooks::MemoryUsage
  # @return [MemoryUsage] a new instance of MemoryUsage
  #
  # pkg:gem/vernier#lib/vernier/hooks/memory_usage.rb:6
  def initialize(collector); end

  # pkg:gem/vernier#lib/vernier/hooks/memory_usage.rb:15
  def disable; end

  # pkg:gem/vernier#lib/vernier/hooks/memory_usage.rb:11
  def enable; end

  # pkg:gem/vernier#lib/vernier/hooks/memory_usage.rb:19
  def firefox_counters; end
end

# pkg:gem/vernier#lib/vernier/marker.rb:3
module Vernier::Marker
  class << self
    # Return an array of marker names.  The index of the string maps to the
    # value of the corresponding constant
    #
    # pkg:gem/vernier#lib/vernier/marker.rb:36
    def name_table; end
  end
end

# pkg:gem/vernier#lib/vernier/marker.rb:13
Vernier::Marker::MARKER_STRINGS = T.let(T.unsafe(nil), Array)

# pkg:gem/vernier#lib/vernier/marker.rb:7
Vernier::Marker::MARKER_SYMBOLS = T.let(T.unsafe(nil), Array)

# pkg:gem/vernier#lib/vernier/marker.rb:3
module Vernier::Marker::Phase; end

Vernier::Marker::Phase::INSTANT = T.let(T.unsafe(nil), Integer)
Vernier::Marker::Phase::INTERVAL = T.let(T.unsafe(nil), Integer)
Vernier::Marker::Phase::INTERVAL_END = T.let(T.unsafe(nil), Integer)
Vernier::Marker::Phase::INTERVAL_START = T.let(T.unsafe(nil), Integer)

# pkg:gem/vernier#lib/vernier/marker.rb:3
module Vernier::Marker::Type; end

Vernier::Marker::Type::FIBER_SWITCH = T.let(T.unsafe(nil), Integer)
Vernier::Marker::Type::GC_END_MARK = T.let(T.unsafe(nil), Integer)
Vernier::Marker::Type::GC_END_SWEEP = T.let(T.unsafe(nil), Integer)
Vernier::Marker::Type::GC_ENTER = T.let(T.unsafe(nil), Integer)
Vernier::Marker::Type::GC_EXIT = T.let(T.unsafe(nil), Integer)
Vernier::Marker::Type::GC_PAUSE = T.let(T.unsafe(nil), Integer)
Vernier::Marker::Type::GC_START = T.let(T.unsafe(nil), Integer)
Vernier::Marker::Type::GVL_THREAD_EXITED = T.let(T.unsafe(nil), Integer)
Vernier::Marker::Type::GVL_THREAD_STARTED = T.let(T.unsafe(nil), Integer)
Vernier::Marker::Type::THREAD_RUNNING = T.let(T.unsafe(nil), Integer)
Vernier::Marker::Type::THREAD_STALLED = T.let(T.unsafe(nil), Integer)
Vernier::Marker::Type::THREAD_SUSPENDED = T.let(T.unsafe(nil), Integer)

# pkg:gem/vernier#lib/vernier/memory_leak_detector.rb:4
class Vernier::MemoryLeakDetector
  # @return [MemoryLeakDetector] a new instance of MemoryLeakDetector
  #
  # pkg:gem/vernier#lib/vernier/memory_leak_detector.rb:11
  def initialize(collect_time:, idle_time: T.unsafe(nil), drain_time: T.unsafe(nil), **collector_options); end

  # pkg:gem/vernier#lib/vernier/memory_leak_detector.rb:36
  def result; end

  # pkg:gem/vernier#lib/vernier/memory_leak_detector.rb:19
  def start_thread; end

  class << self
    # pkg:gem/vernier#lib/vernier/memory_leak_detector.rb:5
    def start_thread(*_arg0, **_arg1, &_arg2); end
  end
end

# pkg:gem/vernier#lib/vernier/marker.rb:3
class Vernier::MemoryTracker
  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def record; end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def results; end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def start; end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def stop; end
end

# pkg:gem/vernier#lib/vernier/middleware.rb:2
class Vernier::Middleware
  # @return [Middleware] a new instance of Middleware
  #
  # pkg:gem/vernier#lib/vernier/middleware.rb:8
  def initialize(app, permit: T.unsafe(nil)); end

  # pkg:gem/vernier#lib/vernier/middleware.rb:13
  def call(env); end
end

# pkg:gem/vernier#lib/vernier/middleware.rb:3
Vernier::Middleware::HOOKS = T.let(T.unsafe(nil), Array)

# pkg:gem/vernier#lib/vernier/output/filename_filter.rb:4
module Vernier::Output; end

# pkg:gem/vernier#lib/vernier/output/cpuprofile.rb:5
class Vernier::Output::Cpuprofile
  # @return [Cpuprofile] a new instance of Cpuprofile
  #
  # pkg:gem/vernier#lib/vernier/output/cpuprofile.rb:6
  def initialize(profile); end

  # pkg:gem/vernier#lib/vernier/output/cpuprofile.rb:10
  def output; end

  private

  # pkg:gem/vernier#lib/vernier/output/cpuprofile.rb:53
  def build_nodes; end

  # pkg:gem/vernier#lib/vernier/output/cpuprofile.rb:128
  def calculate_time_deltas(timestamps); end

  # pkg:gem/vernier#lib/vernier/output/cpuprofile.rb:85
  def create_node_for_stack(stack_idx, nodes, stack_table); end

  # pkg:gem/vernier#lib/vernier/output/cpuprofile.rb:22
  def data; end

  # pkg:gem/vernier#lib/vernier/output/cpuprofile.rb:43
  def empty_profile; end

  # pkg:gem/vernier#lib/vernier/output/cpuprofile.rb:18
  def ns_to_us(timestamp); end

  # Returns the value of attribute profile.
  #
  # pkg:gem/vernier#lib/vernier/output/cpuprofile.rb:16
  def profile; end

  # pkg:gem/vernier#lib/vernier/output/cpuprofile.rb:70
  def root_node; end

  # pkg:gem/vernier#lib/vernier/output/cpuprofile.rb:124
  def stack_to_node_id(stack_idx); end
end

# pkg:gem/vernier#lib/vernier/output/file_listing.rb:8
class Vernier::Output::FileListing
  # @return [FileListing] a new instance of FileListing
  #
  # pkg:gem/vernier#lib/vernier/output/file_listing.rb:23
  def initialize(profile); end

  # pkg:gem/vernier#lib/vernier/output/file_listing.rb:105
  def format_file(output, filename, all_samples, total:); end

  # pkg:gem/vernier#lib/vernier/output/file_listing.rb:134
  def format_file_html(output, filename, relevant_files); end

  # pkg:gem/vernier#lib/vernier/output/file_listing.rb:122
  def html_output(output, relevant_files); end

  # pkg:gem/vernier#lib/vernier/output/file_listing.rb:77
  def output(template: T.unsafe(nil)); end

  # pkg:gem/vernier#lib/vernier/output/file_listing.rb:27
  def samples_by_file; end

  # pkg:gem/vernier#lib/vernier/output/file_listing.rb:100
  def total; end
end

# pkg:gem/vernier#lib/vernier/output/file_listing.rb:9
class Vernier::Output::FileListing::SamplesByLocation
  # @return [SamplesByLocation] a new instance of SamplesByLocation
  #
  # pkg:gem/vernier#lib/vernier/output/file_listing.rb:11
  def initialize; end

  # pkg:gem/vernier#lib/vernier/output/file_listing.rb:15
  def +(other); end

  # Returns the value of attribute self.
  #
  # pkg:gem/vernier#lib/vernier/output/file_listing.rb:10
  def self; end

  # Sets the attribute self
  #
  # @param value the value to set the attribute self to.
  #
  # pkg:gem/vernier#lib/vernier/output/file_listing.rb:10
  def self=(_arg0); end

  # Returns the value of attribute total.
  #
  # pkg:gem/vernier#lib/vernier/output/file_listing.rb:10
  def total; end

  # Sets the attribute total
  #
  # @param value the value to set the attribute total to.
  #
  # pkg:gem/vernier#lib/vernier/output/file_listing.rb:10
  def total=(_arg0); end
end

# pkg:gem/vernier#lib/vernier/output/filename_filter.rb:5
class Vernier::Output::FilenameFilter
  # @return [FilenameFilter] a new instance of FilenameFilter
  #
  # pkg:gem/vernier#lib/vernier/output/filename_filter.rb:6
  def initialize; end

  # pkg:gem/vernier#lib/vernier/output/filename_filter.rb:15
  def call(filename); end

  # Returns the value of attribute gem_match_regex.
  #
  # pkg:gem/vernier#lib/vernier/output/filename_filter.rb:13
  def gem_match_regex; end

  # Returns the value of attribute gem_regex.
  #
  # pkg:gem/vernier#lib/vernier/output/filename_filter.rb:13
  def gem_regex; end

  # Returns the value of attribute pwd.
  #
  # pkg:gem/vernier#lib/vernier/output/filename_filter.rb:13
  def pwd; end

  # Returns the value of attribute rubylibdir.
  #
  # pkg:gem/vernier#lib/vernier/output/filename_filter.rb:13
  def rubylibdir; end
end

# https://profiler.firefox.com/
# https://github.com/firefox-devtools/profiler/blob/main/src/types/profile.ts
#
# pkg:gem/vernier#lib/vernier/output/firefox.rb:12
class Vernier::Output::Firefox
  # @return [Firefox] a new instance of Firefox
  #
  # pkg:gem/vernier#lib/vernier/output/firefox.rb:117
  def initialize(profile); end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:122
  def output(gzip: T.unsafe(nil)); end

  private

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:194
  def counter_data; end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:135
  def data; end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:202
  def marker_schema; end

  # Returns the value of attribute profile.
  #
  # pkg:gem/vernier#lib/vernier/output/firefox.rb:133
  def profile; end
end

# pkg:gem/vernier#lib/vernier/output/firefox.rb:13
class Vernier::Output::Firefox::Categorizer
  # @return [Categorizer] a new instance of Categorizer
  #
  # pkg:gem/vernier#lib/vernier/output/firefox.rb:25
  def initialize; end

  # @yield [category]
  #
  # pkg:gem/vernier#lib/vernier/output/firefox.rb:69
  def add_category(name:, **kw); end

  # Returns the value of attribute categories.
  #
  # pkg:gem/vernier#lib/vernier/output/firefox.rb:23
  def categories; end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:90
  def categorize(path); end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:86
  def gem_path(*names); end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:78
  def get_category(name); end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:82
  def starts_with(*paths); end
end

# pkg:gem/vernier#lib/vernier/output/firefox.rb:18
Vernier::Output::Firefox::Categorizer::AVAILABLE_COLORS = T.let(T.unsafe(nil), Array)

# pkg:gem/vernier#lib/vernier/output/firefox.rb:94
class Vernier::Output::Firefox::Categorizer::Category
  # @raise [ArgumentError]
  # @return [Category] a new instance of Category
  #
  # pkg:gem/vernier#lib/vernier/output/firefox.rb:97
  def initialize(idx, name:, color:, matcher: T.unsafe(nil)); end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:107
  def add_subcategory(**args); end

  # Returns the value of attribute color.
  #
  # pkg:gem/vernier#lib/vernier/output/firefox.rb:95
  def color; end

  # Returns the value of attribute idx.
  #
  # pkg:gem/vernier#lib/vernier/output/firefox.rb:95
  def idx; end

  # Returns the value of attribute matcher.
  #
  # pkg:gem/vernier#lib/vernier/output/firefox.rb:95
  def matcher; end

  # @return [Boolean]
  #
  # pkg:gem/vernier#lib/vernier/output/firefox.rb:111
  def matches?(path); end

  # Returns the value of attribute name.
  #
  # pkg:gem/vernier#lib/vernier/output/firefox.rb:95
  def name; end

  # Returns the value of attribute subcategories.
  #
  # pkg:gem/vernier#lib/vernier/output/firefox.rb:95
  def subcategories; end
end

# This is in the order of preference
#
# pkg:gem/vernier#lib/vernier/output/firefox.rb:21
Vernier::Output::Firefox::Categorizer::ORDERED_CATEGORIES = T.let(T.unsafe(nil), Array)

# pkg:gem/vernier#lib/vernier/output/firefox.rb:14
Vernier::Output::Firefox::Categorizer::RAILS_COMPONENTS = T.let(T.unsafe(nil), Array)

# pkg:gem/vernier#lib/vernier/output/firefox.rb:269
class Vernier::Output::Firefox::Thread
  # @return [Thread] a new instance of Thread
  #
  # pkg:gem/vernier#lib/vernier/output/firefox.rb:272
  def initialize(ruby_thread_id, profile, categorizer, name:, tid:, samples:, weights:, markers:, started_at:, timestamps: T.unsafe(nil), sample_categories: T.unsafe(nil), stopped_at: T.unsafe(nil), allocations: T.unsafe(nil), is_main: T.unsafe(nil), is_start: T.unsafe(nil)); end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:465
  def allocations_table; end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:360
  def categorize_filename(filename); end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:369
  def cfunc_category_and_subcategory; end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:393
  def data; end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:386
  def filter_filenames(filenames); end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:377
  def find_category_and_subcategory(filename, categories); end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:545
  def frame_table; end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:573
  def func_table; end

  # Returns the value of attribute is_start.
  #
  # pkg:gem/vernier#lib/vernier/output/firefox.rb:270
  def is_start; end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:425
  def markers_table; end

  # Returns the value of attribute profile.
  #
  # pkg:gem/vernier#lib/vernier/output/firefox.rb:270
  def profile; end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:373
  def ruby_category_and_subcategory; end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:484
  def samples_table; end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:520
  def stack_table; end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:598
  def string_table; end

  private

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:620
  def gc_category; end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:624
  def thread_category; end
end

# pkg:gem/vernier#lib/vernier/output/markdown.rb:7
class Vernier::Output::Markdown
  # @return [Markdown] a new instance of Markdown
  #
  # pkg:gem/vernier#lib/vernier/output/markdown.rb:11
  def initialize(profile, top_n: T.unsafe(nil), lines_per_file: T.unsafe(nil)); end

  # pkg:gem/vernier#lib/vernier/output/markdown.rb:17
  def output; end

  private

  # pkg:gem/vernier#lib/vernier/output/markdown.rb:185
  def build_files; end

  # pkg:gem/vernier#lib/vernier/output/markdown.rb:79
  def build_hotspots; end

  # pkg:gem/vernier#lib/vernier/output/markdown.rb:33
  def build_summary; end

  # pkg:gem/vernier#lib/vernier/output/markdown.rb:156
  def build_threads; end

  # pkg:gem/vernier#lib/vernier/output/markdown.rb:29
  def build_title; end

  # pkg:gem/vernier#lib/vernier/output/markdown.rb:406
  def escape_markdown(text); end

  # pkg:gem/vernier#lib/vernier/output/markdown.rb:339
  def filter_filename(filename); end

  # pkg:gem/vernier#lib/vernier/output/markdown.rb:392
  def format_code_span(text); end

  # pkg:gem/vernier#lib/vernier/output/markdown.rb:353
  def format_location(file, line); end

  # pkg:gem/vernier#lib/vernier/output/markdown.rb:293
  def get_stack_table(thread); end

  # pkg:gem/vernier#lib/vernier/output/markdown.rb:309
  def get_thread_main(thread); end

  # pkg:gem/vernier#lib/vernier/output/markdown.rb:301
  def get_thread_name(thread); end

  # pkg:gem/vernier#lib/vernier/output/markdown.rb:317
  def get_thread_tid(thread); end

  # pkg:gem/vernier#lib/vernier/output/markdown.rb:277
  def get_threads; end

  # @return [Boolean]
  #
  # pkg:gem/vernier#lib/vernier/output/markdown.rb:348
  def live_profile?; end

  # Helper methods
  #
  # pkg:gem/vernier#lib/vernier/output/markdown.rb:273
  def main_thread; end

  # pkg:gem/vernier#lib/vernier/output/markdown.rb:359
  def read_source_line(filename, line_no); end

  # pkg:gem/vernier#lib/vernier/output/markdown.rb:372
  def resolve_filename(filename); end

  # pkg:gem/vernier#lib/vernier/output/markdown.rb:334
  def thread_count; end

  # pkg:gem/vernier#lib/vernier/output/markdown.rb:134
  def top_functions_table(title, funcs, total, sort_key); end

  # pkg:gem/vernier#lib/vernier/output/markdown.rb:325
  def total_samples; end

  # pkg:gem/vernier#lib/vernier/output/markdown.rb:383
  def truncate_code(code, max_length: T.unsafe(nil)); end
end

# pkg:gem/vernier#lib/vernier/output/markdown.rb:9
Vernier::Output::Markdown::DEFAULT_LINES_PER_FILE = T.let(T.unsafe(nil), Integer)

# pkg:gem/vernier#lib/vernier/output/markdown.rb:8
Vernier::Output::Markdown::DEFAULT_TOP_N = T.let(T.unsafe(nil), Integer)

# pkg:gem/vernier#lib/vernier/output/top.rb:5
class Vernier::Output::Top
  # @return [Top] a new instance of Top
  #
  # pkg:gem/vernier#lib/vernier/output/top.rb:6
  def initialize(profile, row_limit); end

  # pkg:gem/vernier#lib/vernier/output/top.rb:51
  def output; end
end

# pkg:gem/vernier#lib/vernier/output/top.rb:11
class Vernier::Output::Top::Table
  # @return [Table] a new instance of Table
  # @yield [_self]
  # @yieldparam _self [Vernier::Output::Top::Table] the object that the method was called on
  #
  # pkg:gem/vernier#lib/vernier/output/top.rb:12
  def initialize(header, row_limit); end

  # pkg:gem/vernier#lib/vernier/output/top.rb:19
  def <<(row); end

  # pkg:gem/vernier#lib/vernier/output/top.rb:46
  def format_row(row); end

  # pkg:gem/vernier#lib/vernier/output/top.rb:42
  def row_separator; end

  # pkg:gem/vernier#lib/vernier/output/top.rb:23
  def to_s; end

  # pkg:gem/vernier#lib/vernier/output/top.rb:35
  def widths; end
end

# pkg:gem/vernier#lib/vernier/parsed_profile.rb:7
class Vernier::ParsedProfile
  # @return [ParsedProfile] a new instance of ParsedProfile
  #
  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:87
  def initialize(data); end

  # Returns the value of attribute data.
  #
  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:86
  def data; end

  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:98
  def main_thread; end

  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:91
  def threads; end

  class << self
    # pkg:gem/vernier#lib/vernier/parsed_profile.rb:8
    def read_file(filename); end
  end
end

# pkg:gem/vernier#lib/vernier/parsed_profile.rb:24
class Vernier::ParsedProfile::StackTable
  include ::Vernier::StackTableHelpers

  # @return [StackTable] a new instance of StackTable
  #
  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:25
  def initialize(thread_data); end

  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:39
  def frame_count; end

  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:45
  def frame_func_idx(idx); end

  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:46
  def frame_line_no(idx); end

  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:40
  def func_count; end

  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:51
  def func_filename(idx); end

  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:49
  def func_filename_idx(idx); end

  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:52
  def func_first_lineno(idx); end

  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:50
  def func_name(idx); end

  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:48
  def func_name_idx(idx); end

  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:38
  def stack_count; end

  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:43
  def stack_frame_idx(idx); end

  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:42
  def stack_parent_idx(idx); end

  # Returns the value of attribute strings.
  #
  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:36
  def strings; end
end

# pkg:gem/vernier#lib/vernier/parsed_profile.rb:57
class Vernier::ParsedProfile::Thread
  # @return [Thread] a new instance of Thread
  #
  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:60
  def initialize(data); end

  # Emulate hash
  #
  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:81
  def [](name); end

  # Returns the value of attribute data.
  #
  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:58
  def data; end

  # @return [Boolean]
  #
  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:68
  def main_thread?; end

  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:72
  def samples; end

  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:64
  def stack_table; end

  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:76
  def weights; end
end

# pkg:gem/vernier#lib/vernier/marker.rb:3
class Vernier::Result
  # Returns the value of attribute stack_table.
  #
  # pkg:gem/vernier#lib/vernier/result.rb:6
  def _stack_table; end

  # pkg:gem/vernier#lib/vernier/result.rb:70
  def each_sample; end

  # pkg:gem/vernier#lib/vernier/result.rb:62
  def elapsed_seconds; end

  # Returns the value of attribute end_time.
  #
  # pkg:gem/vernier#lib/vernier/result.rb:8
  def end_time; end

  # Sets the attribute end_time
  #
  # @param value the value to set the attribute end_time to.
  #
  # pkg:gem/vernier#lib/vernier/result.rb:8
  def end_time=(_arg0); end

  # Returns the value of attribute gc_markers.
  #
  # pkg:gem/vernier#lib/vernier/result.rb:10
  def gc_markers; end

  # Returns the value of attribute hooks.
  #
  # pkg:gem/vernier#lib/vernier/result.rb:8
  def hooks; end

  # Sets the attribute hooks
  #
  # @param value the value to set the attribute hooks to.
  #
  # pkg:gem/vernier#lib/vernier/result.rb:8
  def hooks=(_arg0); end

  # pkg:gem/vernier#lib/vernier/result.rb:66
  def inspect; end

  # pkg:gem/vernier#lib/vernier/result.rb:12
  def main_thread; end

  # Returns the value of attribute meta.
  #
  # pkg:gem/vernier#lib/vernier/result.rb:10
  def meta; end

  # Returns the value of attribute pid.
  #
  # pkg:gem/vernier#lib/vernier/result.rb:8
  def pid; end

  # Sets the attribute pid
  #
  # @param value the value to set the attribute pid to.
  #
  # pkg:gem/vernier#lib/vernier/result.rb:8
  def pid=(_arg0); end

  # pkg:gem/vernier#lib/vernier/result.rb:79
  def stack(idx); end

  # Returns the value of attribute stack_table.
  #
  # pkg:gem/vernier#lib/vernier/result.rb:5
  def stack_table; end

  # Sets the attribute stack_table
  #
  # @param value the value to set the attribute stack_table to.
  #
  # pkg:gem/vernier#lib/vernier/result.rb:5
  def stack_table=(_arg0); end

  # Realtime in nanoseconds since the unix epoch
  #
  # pkg:gem/vernier#lib/vernier/result.rb:17
  def started_at; end

  # Returns the value of attribute threads.
  #
  # pkg:gem/vernier#lib/vernier/result.rb:10
  def threads; end

  # pkg:gem/vernier#lib/vernier/result.rb:29
  def to_cpuprofile; end

  # pkg:gem/vernier#lib/vernier/result.rb:24
  def to_firefox(gzip: T.unsafe(nil)); end

  # pkg:gem/vernier#lib/vernier/result.rb:27
  def to_gecko(gzip: T.unsafe(nil)); end

  # pkg:gem/vernier#lib/vernier/result.rb:33
  def to_markdown(top_n: T.unsafe(nil), lines_per_file: T.unsafe(nil)); end

  # pkg:gem/vernier#lib/vernier/result.rb:87
  def total_bytes; end

  # pkg:gem/vernier#lib/vernier/result.rb:95
  def total_samples; end

  # pkg:gem/vernier#lib/vernier/result.rb:99
  def total_unique_samples; end

  # pkg:gem/vernier#lib/vernier/result.rb:83
  def total_weights; end

  # pkg:gem/vernier#lib/vernier/result.rb:37
  def write(out:, format: T.unsafe(nil)); end
end

# pkg:gem/vernier#lib/vernier/marker.rb:3
class Vernier::StackTable
  include ::Vernier::StackTableHelpers

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def convert(_arg0, _arg1); end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def current_stack(*_arg0); end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def finalize; end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def frame_count; end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def frame_func_idx(_arg0); end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def frame_line_no(_arg0); end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def func_absolute_path(_arg0); end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def func_count; end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def func_filename(_arg0); end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def func_first_lineno(_arg0); end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def func_name(_arg0); end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def func_path(_arg0); end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def stack_count; end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def stack_frame_idx(_arg0); end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def stack_parent_idx(_arg0); end

  class << self
    # pkg:gem/vernier#lib/vernier/marker.rb:3
    def new; end
  end
end

# pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:2
module Vernier::StackTableHelpers
  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:25
  def backtrace(stack_idx); end

  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:43
  def full_stack(stack_idx); end

  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:3
  def inspect; end

  # @raise [ArgumentError]
  #
  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:149
  def stack(idx); end

  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:7
  def to_h; end
end

# pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:52
class Vernier::StackTableHelpers::BaseType
  # @return [BaseType] a new instance of BaseType
  #
  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:54
  def initialize(stack_table, idx); end

  # Returns the value of attribute idx.
  #
  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:53
  def idx; end

  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:59
  def inspect; end

  # Returns the value of attribute stack_table.
  #
  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:53
  def stack_table; end
end

# pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:79
class Vernier::StackTableHelpers::Frame < ::Vernier::StackTableHelpers::BaseType
  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:81
  def filename; end

  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:84
  def func; end

  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:80
  def label; end

  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:89
  def line; end

  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:92
  def lineno; end

  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:82
  def name; end

  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:94
  def to_s; end
end

# pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:64
class Vernier::StackTableHelpers::Func < ::Vernier::StackTableHelpers::BaseType
  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:70
  def filename; end

  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:65
  def label; end

  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:68
  def name; end

  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:74
  def to_s; end
end

# pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:103
class Vernier::StackTableHelpers::Stack < ::Vernier::StackTableHelpers::BaseType
  # @raise [RangeError]
  #
  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:116
  def [](offset); end

  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:104
  def each; end

  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:114
  def each_frame; end

  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:136
  def frames; end

  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:132
  def leaf_frame; end

  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:128
  def leaf_frame_idx; end

  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:140
  def to_s; end
end

# Collects names of all seen threads
#
# pkg:gem/vernier#lib/vernier/thread_names.rb:3
class Vernier::ThreadNames
  # @return [ThreadNames] a new instance of ThreadNames
  #
  # pkg:gem/vernier#lib/vernier/thread_names.rb:4
  def initialize; end

  # pkg:gem/vernier#lib/vernier/thread_names.rb:12
  def [](object_id); end

  # pkg:gem/vernier#lib/vernier/thread_names.rb:16
  def finish; end

  private

  # pkg:gem/vernier#lib/vernier/thread_names.rb:23
  def collect_running; end

  # pkg:gem/vernier#lib/vernier/thread_names.rb:29
  def collect_thread(th); end

  # pkg:gem/vernier#lib/vernier/thread_names.rb:33
  def pretty_name(thread); end
end

# pkg:gem/vernier#lib/vernier/version.rb:4
Vernier::VERSION = T.let(T.unsafe(nil), String)
