version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "sorbet"
      - dependency-name: "sorbet-runtime"
    reviewers:
      - "Shopify/sorbet"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "Shopify/sorbet"
