# This file strictly follows the rules defined in the Ruby style guide:
#   http://shopify.github.io/ruby-style-guide/
inherit_gem:
  rubocop-shopify: rubocop.yml

require:
 - rubocop-sorbet

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
  - "vendor/**/*"
  - "spec/support/repo/bin/tapioca"

Style/CaseEquality:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
  - "spec/tapioca/**/*"

Sorbet:
  Enabled: true

Sorbet/FalseSigil:
  Enabled: false

Sorbet/TrueSigil:
  Enabled: true
  Include:
  - "**/*.rb"
  Exclude:
  - "spec/support/gems/baz/lib/baz.rb"

Sorbet/ConstantsFromStrings:
  Enabled: false
