name: tapioca

nix: true
type: ruby

up:
  - ruby
  - bundler
  - packages:
      - libyaml
      - zlib

env:
  SRB_SKIP_GEM_RBIS: 'true'

commands:
  typecheck:
    aliases: [ "tc" ]
    run:     "bin/typecheck"
  console:   "bin/console"
  test:      "bin/test"
  style:     "bin/style"
  docs:      "bin/docs"
  sanity:    "bin/typecheck && bin/style && bin/test"
