# typed: strict
# frozen_string_literal: true

require "tapioca"
require "tapioca/loader"
require "tapioca/sorbet_ext/generic_name_patch"
require "tapioca/sorbet_ext/fixed_hash_patch"
require "tapioca/generic_type_registry"
require "tapioca/helpers/cli_helper"
require "tapioca/helpers/config_helper"
require "tapioca/helpers/shims_helper"
require "tapioca/helpers/sorbet_helper"
require "tapioca/generators"
require "tapioca/cli"
require "tapioca/gemfile"
require "tapioca/executor"
require "tapioca/symbol_table_parser"
require "tapioca/symbol_loader"
require "tapioca/compilers/gem/events"
require "tapioca/compilers/gem/listeners/base"
require "tapioca/compilers/gem/listeners/dynamic_mixins"
require "tapioca/compilers/gem/listeners/methods"
require "tapioca/compilers/gem/listeners/mixins"
require "tapioca/compilers/gem/listeners/sorbet_enums"
require "tapioca/compilers/gem/listeners/sorbet_helpers"
require "tapioca/compilers/gem/listeners/sorbet_props"
require "tapioca/compilers/gem/listeners/sorbet_required_ancestors"
require "tapioca/compilers/gem/listeners/sorbet_signatures"
require "tapioca/compilers/gem/listeners/sorbet_type_variables"
require "tapioca/compilers/gem/listeners/yard_doc"
require "tapioca/compilers/requires_compiler"
require "tapioca/compilers/symbol_table_compiler"
require "tapioca/compilers/dsl_compiler"
