name: Table of Contents Generator

on: push

jobs:
  toc:
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v4
        with:
          TOC_TITLE: "## Table of Contents"
